version: '3.7'
services:
  ldap_server:
      image: openldap:withdata
      environment:
        LDAP_ADMIN_PASSWORD: password
        LDAP_BASE_DN: dc=gitlab,dc=local
        LDAP_DOMAIN: gitlab.local 
      ports:
        - 389:389
      volumes:
        - ldap_data:/var/lib/ldap
        - ldap_config:/etc/ldap/slapd.d
        - ./bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
      command: [--copy-service,  --loglevel, debug]

  ldap_server_admin:
      image: osixia/phpldapadmin
      ports:
        - 8090:80
      environment:
        PHPLDAPADMIN_LDAP_HOSTS: ldap_server
        PHPLDAPADMIN_HTTPS: 'false'
volumes:
  ldap_data:
  ldap_config: